default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        exclude: ^k8s/
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py39-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: test
        name: pytest
        entry: poetry run pytest -c pyproject.toml .
        types: [ python ]
        language: system

  - repo: local
    hooks:
        - id: bandit
          name: bandit
          entry: poetry run bandit --exclude tests .
          types: [ python ]
          language: system

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.8
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
