apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-python-chart.fullname" . }}
  labels:
    {{- include "app-python-chart.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
