version: '3.9'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '10'
    tag: "{{.ImageName}}|{{.Name}}"

x-defaults:
  &defaults
  logging: *default-logging
  restart: unless-stopped

networks:
  loki:

volumes:
  grafana-data:
  loki-data:
  promtail-data:

services:

  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    <<: *defaults

  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    volumes:
      - loki-data:/tmp/loki/
    <<: *defaults

  promtail:
    image: grafana/promtail:2.3.0
    ports:
      - 9080:9080
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - promtail-data:/var/lib/promtail/positions
    <<: *defaults
