apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: winnerokay/app_python:latest
        ports:
        - containerPort: 8000
