apiVersion: v1
kind: Service
metadata:
  name: my-app-python-service
spec:
  selector:
    app: app-python
  type: LoadBalancer
  ports:
    - protocol: TCP
      # outer port
      port: 8888
      # inner port
      targetPort: 8000
