version: '2.4'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '10'
    tag: "{{.ImageName}}|{{.Name}}"

x-resources:
  &default-resources
  cpus: 0.5
  mem_limit: 128M

x-defaults:
  &defaults
  logging: *default-logging
  restart: unless-stopped
  <<: *default-resources

networks:
  app:

services:
  python_app:
    image: winnerokay/app_python:${TAG:-latest}
    ports:
      - "${OUTER_PORT:-8000}:8000"
    networks:
      - app
    <<: *defaults
