version: '2.4'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '10'
    tag: "{{.ImageName}}|{{.Name}}"

x-resources:
  &default-resources
  cpus: 0.5
  mem_limit: 128M

x-healthcheck:
  &default-healthcheck
  test: [ "CMD", "curl", "-f", "http://localhost" ]
  interval: 10s  # consider greater interval
  timeout: 10s
  retries: 3
  start_period: 40s

x-defaults:
  &defaults
  logging: *default-logging
  restart: unless-stopped
  <<: *default-resources

networks:
  app:

services:
  python_app:
    image: winnerokay/app_python:${TAG:-latest}
    ports:
      - "${OUTER_PORT:-8000}:8000"
    networks:
      - app
    volumes:
      - ./media:/home/moscow_clock/media
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
    <<: *defaults
