---
- name: Ensure directory for application
  become: true
  file:
    owner: "{{ ansible_user_id }}"
    path: "{{ python_app_folder }}"
    state: directory
    mode: 0755

- name: Copy docker-compose
  template:
    src: template/docker-compose.yml.j2
    dest: "{{ python_app_folder }}/docker-compose.yaml"
    mode: u=rw,g=r,o=r

- name: Run docker-compose
  become: true
  community.docker.docker_compose:
    pull: true
    recreate: always
    state: present
    project_src: "{{ python_app_folder }}"
