---
- name: Ensure directory for application
  become: true
  file:
    owner: "{{ ansible_user_id }}"
    path: /opt/python_app/
    state: directory
    mode: 0755

#- name: Copy docker-compose
#  copy:
#    src: ../../../../docker/docker-compose.yaml
#    dest: /opt/python_app/docker-compose.yaml
#    mode: u=rw,g=r,o=r

- name: Copy docker-compose
  template:
    src: template/docker-compose.yml.j2
    dest: /opt/python_app/docker-compose.yaml
    mode: u=rw,g=r,o=r

- name: Run docker-compose
  become: true
  community.docker.docker_compose:
    pull: true
    recreate: always
    state: present
    project_src: /opt/python_app/
  environment:
    TAG: "{{ python_app_tag }}"
    OUTER_PORT: "{{python_app_outer_port}}"
