---
- hosts: all
  remote_user: ubuntu
  vars:
    python_app_docker_tag: latest

  roles:
    - role: ubuntu20_docker_install
      become: true
      vars:
        docker_users:
          - "{{ ansible_user_id }}"
    - role: deploy_app
      vars:
        python_app_tag: "{{ python_app_docker_tag }}"
