Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provider "virtualbox" do |v|
    v.name = "devops_lab"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/provision_app.yml"
    ansible.extra_vars = {
      username: "vagrant",
      python_app_tag: "terraform",
      python_app_outer_port: "8000",
    }
  end

end
