Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian10"

  config.vm.provider "virtualbox" do |v|
    v.name = "devops_lab"
    v.memory = 2048
    v.cpus = 2
  end
end
